FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY ["CarApi/CarApi.csproj", "CarApi/"]
RUN dotnet restore "CarApi/CarApi.csproj"
COPY . .
WORKDIR "/src/CarApi"
RUN dotnet build "CarApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CarApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CarApi.dll"]